name = "k4e"
description = "RHEL for Edge"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "yggdrasil"
version = "*"

[[packages]]
name = "k4e-agent"
version = "*"

[[packages]]
name = "dmidecode"
version = "*"

[[packages]]
name = "ipmitool"
version = "*"

[[packages]]
name = "smartmontools"
version = "*"

[[packages]]
name = "file"
version = "*"

[[packages]]
name = "util-linux"
version = "*"

[customizations.services]
enabled = ["nftables", "podman.socket", "podman"]
disabled = ["firewalld"]
