name = "flotta"
description = "Flotta RHEL for Edge"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "yggdrasil"
version = "*"

[[packages]]
name = "flotta-agent"
version = "*"

[[packages]]
name = "dmidecode"
version = "*"

[[packages]]
name = "ipmitool"
version = "*"

[[packages]]
name = "smartmontools"
version = "*"

[[packages]]
name = "file"
version = "*"

[[packages]]
name = "util-linux"
version = "*"

[[packages]]
name = "node_exporter"
version = "*"

[customizations.services]
enabled = ["nftables", "podman.socket", "podman", "node_exporter"]
disabled = ["firewalld"]
