---
kubevirtCR:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    deployOVS: "false"
  labels:
    app: kubevirt-cr
  featureGates:
    - DataVolume  
cnv:
  debug:
    useEmulation: "false"
