---
nexus:
  allowAnonymousAccess: true
  service: nexus
  oauth:
    enabled: true
    bypassAuthFor:
      - "/repository"
    adminUsers: []
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1
      memory: 2048Mi
  expose:
    ssl: true
    kind: Route
  persistent:
    enabled: true
    volumeSize: 100Gi
  image:
    registry: quay.io
    repository: jordigilh/nexus-operator
    version: 0.0.11
    imagePullPolicy: IfNotPresent
  jvm:
    memory: 512m

setup:
  repositories:
    - rfe-kickstarts
    - rfe-tarballs
    - rfe-rhel-media
    - rfe-auto-iso
  rfe:
    username: rfe-automation
    secretName: nexus-rfe-credentials

  image:
    registry: registry.redhat.io
    repository: openshift4/ose-cli
    version: v4.6
    imagePullPolicy: IfNotPresent

setupJob:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
