---
defaultsConfigmap:
  annotations:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines

commonCR:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    rgocd.argoproj.io/sync-wave: "5"
